version: '3'
services:
  phensim.fpm:
    image: ghcr.io/alaimos/phensim-fpm_server:v1.0.0
    environment:
      APP_DEBUG: "false"
      APP_KEY: "base64:voAFAEAk+LjyUyA6rf8mXXo4wr9LrKu/obePKnZzK9M="
      APP_URL: "http://localhost"
      FRONTEND_URL: "http://localhost:3000"
      DISABLE_RATE_LIMIT: "true"
      DB_HOST: "mysql"
      DB_PORT: 3306
      DB_DATABASE: "phensim"
      DB_USERNAME: "phensim"
      DB_PASSWORD: "phensim"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      REDIS_PASSWORD: null
    volumes:
      - 'phensim-storage:/opt/apps/phensim/storage/'
    networks:
      - phensim-network
  phensim.web:
    image: ghcr.io/alaimos/phensim-web_server:v1.0.0
    ports:
      - '8080:80'
    environment:
      FPM_HOST: "phensim.fpm:9000"
      APP_KEY: "base64:voAFAEAk+LjyUyA6rf8mXXo4wr9LrKu/obePKnZzK9M="
      APP_DEBUG: "false"
      APP_URL: "http://localhost"
      FRONTEND_URL: "http://localhost:3000"
      DISABLE_RATE_LIMIT: "true"
      DB_HOST: "mysql"
      DB_PORT: 3306
      DB_DATABASE: "phensim"
      DB_USERNAME: "phensim"
      DB_PASSWORD: "phensim"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      REDIS_PASSWORD: null
    volumes:
      - 'phensim-storage:/opt/apps/phensim/storage/'
    networks:
      - phensim-network
  phensim.cron:
    image: ghcr.io/alaimos/phensim-cron:v1.0.0
    volumes:
      - 'phensim-storage:/opt/apps/phensim/storage/'
    networks:
      - phensim-network
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "phensim"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "phensim"
      MYSQL_USER: "phensim"
      MYSQL_PASSWORD: "phensim"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'phensim-mysql:/var/lib/mysql'
    networks:
      - phensim-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-pphensim" ]
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'phensim-redis:/data'
    networks:
      - phensim-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s
networks:
  phensim-network:
volumes:
  phensim-mysql:
    driver: local
  phensim-redis:
    driver: local
  phensim-storage:
    driver: local
