#!/usr/bin/env bash

if [ -n "$WWWUSER" ]; then
    usermod -u "$WWWUSER" phensim
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ];then
    exec gosu "$WWWUSER" "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
